### ISSUE TITLE
knn

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-nearest#4]
We should use [sphere-knn](https://github.com/darkskyapp/sphere-knn) for much performance boost and >1 result possibilities.

**Comment by tmcw** [comment]
great notes on efficiency here: https://github.com/mikolalysenko/static-kdtree#static-kdtree

**Comment by jvrousseau** [comment]
@tmcw implemented here: 67f81f4047ba56d8d0a3a1e9d60d4c5a5d917fdf (tests are passing)

However, it looks like performance took a pretty big hit:
Using turf-distance:

![screen shot 2015-03-17 at 3 16 02 pm](https://cloud.githubusercontent.com/assets/1713751/6696930/e45fcaf6-ccba-11e4-8c14-31c54465bc7b.png)

Using sphere-knn:

![screen shot 2015-03-17 at 3 27 11 pm](https://cloud.githubusercontent.com/assets/1713751/6697217/25e70014-ccbd-11e4-877e-db5033bda9ab.png)

I think our options here are either:
- implement knn internally and optimize it for a FeatureCollection (sphere-knn uses an array of lat/lng objects so that would cut down on some pre/post-processing that has to be done, see: https://github.com/jvrousseau/turf-nearest/blob/master/index.js#L65).
- look at optimizing sphere-knn (although the codebase hasn't been updated for a couple of years).

I can take a stab at the first option, but I would like to hear what your all's opinions are before I went down a rabbit hole.

cc @morganherlocker

**Comment by tmcw** [comment]
The trick with this / all indexes will be separating index creation, which is bound to be somewhat slow, from the usage of the index. benchmarking (creating index, querying) vs (naive search) will likely favor naive search.

**Comment by jvrousseau** [comment]
Gotcha, totally makes sense (sorry I bugged you on that one). So something like an index module discussed in Turfjs/turf#173 would be the linchpin to be able to fully realize the performance gain from shpere-knn implementation.

**Comment by tmcw** [comment]
Oh - not at all, your branch is probably a good place to start for experimenting with this API!

**Comment by jvrousseau** [comment]
cool. thanks a lot for the guidance!

**Comment by jvrousseau** [comment]
@tmcw, I've been experimenting with some indexing concepts. I found [RBush](https://github.com/mourner/rbush) best supported the concept that I wanted to prove, so I took off running with that.

My plan was to work on a knn for RBush, but then I saw that @mourner beat me to the point :+1: 

So here's my basic proof of concept that went into [turf-index](https://github.com/jvrousseau/turf-index):
- append a JSON representation of the index to the features array of a FeatureCollection
  - we want to keep the FeatureCollection valid GeoJSON. To do that, I create a feature with `null` geometry and the jsonified rtree as a field in the properties object.
- turf modules will then be able to check for null geometries plus some identifier (for now it's just "rtree") in the properties of the feature to fork the process.
- I've updated a fork of [turf-nearest](https://github.com/jvrousseau/turf-nearest) to demonstrate my concept.
  - this can support >1 results, but for testing I kept it at one result
  - updated benchmarks for turf-nearest:
    ![benchmark](https://cloud.githubusercontent.com/assets/1713751/7433875/60837d04-effb-11e4-9a5f-3ed41ae32f38.png)

Things that I still need to consider:
- keeping the index consistent with the feature collection.
  - as of now I added`feature_index` property the the rtree to reference the features in the index
- large datasets (just haven't tested)
- adding/removing points on-the-fly (rather than re-indexing)
- using this in modules other than turf-nearest
- other indexing strategies:
  - quadtree (using [tile-cover](https://github.com/mapbox/tile-cover)?)
  - kd-tree (pull datastructure out of [shpere-knn](https://github.com/darkskyapp/sphere-knn)?)

Anyways, if you think this is something that would be helpful for turf, please let me know. I can start tinkering around with some of the above considerations. If not, no big deal at all...I'll just keep on playing around! :smile:

**Comment by mourner** [comment]
@jvrousseau happy to see my rbush-knn already being useful and looking fast. :) Nice work!

**Comment by tmcw** [comment]
Merging into https://github.com/Turfjs/turf/issues/173
